In [3]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

from warnings import filterwarnings
filterwarnings(action='ignore')

In [4]:
data = pd.read_csv('WineQT.csv')
data

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4             0.700         0.00             1.9      0.076   
1               7.8             0.880         0.00             2.6      0.098   
2               7.8             0.760         0.04             2.3      0.092   
3              11.2             0.280         0.56             1.9      0.075   
4               7.4             0.700         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
1138            6.3             0.510         0.13             2.3      0.076   
1139            6.8             0.620         0.08             1.9      0.068   
1140            6.2             0.600         0.08             2.0      0.090   
1141            5.9             0.550         0.10             2.2      0.062   
1142            5.9             0.645         0.12             2.0      0.075   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    11.0                  34.0  0.99780  3.51       0.56   
1                    25.0                  67.0  0.99680  3.20       0.68   
2                    15.0                  54.0  0.99700  3.26       0.65   
3                    17.0                  60.0  0.99800  3.16       0.58   
4                    11.0                  34.0  0.99780  3.51       0.56   
...                   ...                   ...      ...   ...        ...   
1138                 29.0                  40.0  0.99574  3.42       0.75   
1139                 28.0                  38.0  0.99651  3.42       0.82   
1140                 32.0                  44.0  0.99490  3.45       0.58   
1141                 39.0                  51.0  0.99512  3.52       0.76   
1142                 32.0                  44.0  0.99547  3.57       0.71   

      alcohol  quality    Id  
0         9.4        5     0  
1         9.8        5     1  
2         9.8        5     2  
3         9.8        6     3  
4         9.4        5     4  
...       ...      ...   ...  
1138     11.0        6  1592  
1139      9.5        6  1593  
1140     10.5        5  1594  
1141     11.2        6  1595  
1142     10.2        5  1597  

[1143 rows x 13 columns]

In [5]:
c = data.values
x = c[:,1:11]
y = c[:,11]
x,y

(array([[ 0.7  ,  0.   ,  1.9  , ...,  3.51 ,  0.56 ,  9.4  ],
        [ 0.88 ,  0.   ,  2.6  , ...,  3.2  ,  0.68 ,  9.8  ],
        [ 0.76 ,  0.04 ,  2.3  , ...,  3.26 ,  0.65 ,  9.8  ],
        ...,
        [ 0.6  ,  0.08 ,  2.   , ...,  3.45 ,  0.58 , 10.5  ],
        [ 0.55 ,  0.1  ,  2.2  , ...,  3.52 ,  0.76 , 11.2  ],
        [ 0.645,  0.12 ,  2.   , ...,  3.57 ,  0.71 , 10.2  ]]),
 array([5., 5., 5., ..., 5., 6., 5.]))

In [6]:
len(set(y))

6

In [43]:
Y = data['quality'].apply(lambda y: 1 if y>=7 else 0)
Y

0       0
1       0
2       0
3       0
4       0
       ..
1138    0
1139    0
1140    0
1141    0
1142    0
Name: quality, Length: 1143, dtype: int64

In [10]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(x)
x = scaler.transform(x)

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(x,Y, test_size = 0.2, random_state= 4)

In [16]:
X_train

array([[ 0.71655875, -0.04254305, -0.61398759, ..., -1.0282215 ,
         0.48315057, -1.14827218],
       [-0.06314838, -1.16156762, -0.24507216, ...,  0.56824825,
        -0.16267679, -0.96338181],
       [ 0.38239855,  0.16091596,  1.45193879, ..., -0.07033965,
         3.0077484 , -0.22382033],
       ...,
       [ 2.38735976, -0.34773157, -0.39263833, ...,  0.31281309,
        -1.27819676,  0.42329596],
       [-1.28840246,  1.12734627,  0.93545719, ..., -0.26191602,
        -0.10396521,  1.53263818],
       [-0.56438869,  0.61869874, -0.24507216, ..., -2.68855005,
        -0.92592729, -0.77849144]])

In [49]:
from sklearn.linear_model import LogisticRegression
model_LR=LogisticRegression()
model_LR.fit(X_train,Y_train)

LogisticRegression()

In [50]:
prediction = model_LR.predict(X_test)

from sklearn.metrics import accuracy_score
print(accuracy_score(Y_test, prediction)*100)

86.02620087336244


In [53]:
model = RandomForestClassifier()
model.fit(X_train, Y_train)
pred = model.predict(X_test)
test_data_accuracy = accuracy_score(pred, Y_test)

In [54]:
test_data_accuracy

0.8951965065502183

In [59]:
from sklearn.ensemble import RandomForestClassifier
model_tt = RandomForestClassifier(n_estimators=50,max_depth=3)
model_tt.fit(X_train,Y_train)

RandomForestClassifier(max_depth=3, n_estimators=50)

In [60]:
prediction = model_tt.predict(X_test)

from sklearn.metrics import accuracy_score
print(accuracy_score(Y_test, prediction)*100)

86.02620087336244


In [61]:
from sklearn.tree import DecisionTreeClassifier
model_ls = DecisionTreeClassifier()
model_ls.fit(X_train,Y_train)

DecisionTreeClassifier()

In [62]:
prediction = model_ls.predict(X_test)

from sklearn.metrics import accuracy_score
print(accuracy_score(Y_test, prediction)*100)

86.46288209606988
